# Static lookup tables for HotS internal hero and map identifiers.
# Internal names come from tracker events (SUnitBornEvent, EndOfGameTalentChoices)
# and are always English regardless of client language.

# Internal hero ID -> English display name.
# Keys are the unit type name with the "Hero" prefix stripped (from SUnitBornEvent).
# Variant forms (DVaMech, DVaPilot) are included for robustness.
HERO_NAMES = {
	"Abathur": "Abathur",
	"Alarak": "Alarak",
	"Alexstrasza": "Alexstrasza",
	"AlexstraszaDragon": "Alexstrasza",
	"Amazon": "Cassia",
	"Ana": "Ana",
	"Anduin": "Anduin",
	"Anubarak": "Anub'arak",
	"Artanis": "Artanis",
	"Arthas": "Arthas",
	"Auriel": "Auriel",
	"Azmodan": "Azmodan",
	"Barbarian": "Sonya",
	"Butcher": "The Butcher",
	"Chen": "Chen",
	"Cho": "Cho",
	"Chromie": "Chromie",
	"Crusader": "Johanna",
	"DVa": "D.Va",
	"DVaMech": "D.Va",
	"DVaPilot": "D.Va",
	"Deathwing": "Deathwing",
	"Deckard": "Deckard",
	"Dehaka": "Dehaka",
	"DemonHunter": "Valla",
	"Diablo": "Diablo",
	"Dryad": "Lunara",
	"FaerieDragon": "Brightwing",
	"Falstad": "Falstad",
	"Fenix": "Fenix",
	"Firebat": "Blaze",
	"Gall": "Gall",
	"Garrosh": "Garrosh",
	"Genji": "Genji",
	"Greymane": "Greymane",
	"Guldan": "Gul'dan",
	"Hanzo": "Hanzo",
	"Hogger": "Hogger",
	"Imperius": "Imperius",
	"Illidan": "Illidan",
	"Jaina": "Jaina",
	"Junkrat": "Junkrat",
	"Kaelthas": "Kael'thas",
	"KelThuzad": "Kel'Thuzad",
	"Kerrigan": "Kerrigan",
	"L90ETC": "E.T.C.",
	"Leoric": "Leoric",
	"LiLi": "Li Li",
	"LostVikings": "The Lost Vikings",
	"LostVikingsController": "The Lost Vikings",
	"Lucio": "Lúcio",
	"Maiev": "Maiev",
	"MalGanis": "Mal'Ganis",
	"Malfurion": "Malfurion",
	"Malthael": "Malthael",
	"Medic": "Lt. Morales",
	"Medivh": "Medivh",
	"MedivhRaven": "Medivh",
	"MeiOW": "Mei",
	"Mephisto": "Mephisto",
	"Monk": "Kharazim",
	"Muradin": "Muradin",
	"Murky": "Murky",
	"Necromancer": "Xul",
	"NexusHunter": "Qhira",
	"Nova": "Nova",
	"Orphea": "Orphea",
	"Probius": "Probius",
	"Ragnaros": "Ragnaros",
	"Raynor": "Raynor",
	"Rehgar": "Rehgar",
	"Rexxar": "Rexxar",
	"Samuro": "Samuro",
	"SgtHammer": "Sgt. Hammer",
	"Stitches": "Stitches",
	"Stukov": "Stukov",
	"Sylvanas": "Sylvanas",
	"Tassadar": "Tassadar",
	"Thrall": "Thrall",
	"Tinker": "Gazlowe",
	"Tracer": "Tracer",
	"Tychus": "Tychus",
	"Tyrael": "Tyrael",
	"Tyrande": "Tyrande",
	"Uther": "Uther",
	"Valeera": "Valeera",
	"Varian": "Varian",
	"Whitemane": "Whitemane",
	"WitchDoctor": "Nazeebo",
	"Wizard": "Li-Ming",
	"Yrel": "Yrel",
	"Zagara": "Zagara",
	"Zarya": "Zarya",
	"Zeratul": "Zeratul",
	"Zuljin": "Zul'jin",
}

# Internal map ID -> English display name.
# Keys are from EndOfGameTalentChoices "Map" field in tracker events.
MAP_NAMES = {
	"AlteracPass": "Alterac Pass",
	"BattlefieldOfEternity": "Battlefield of Eternity",
	"BlackheartsBay": "Blackheart's Bay",
	"BraxisHoldout": "Braxis Holdout",
	"BraxisOutpost": "Braxis Outpost",
	"ControlPoints": "Sky Temple",
	"Crypts": "Tomb of the Spider Queen",
	"CursedHollow": "Cursed Hollow",
	"CursedHollowSandbox": "Cursed Hollow (Sandbox)",
	"DragonShire": "Dragon Shire",
	"Hanamura": "Hanamura Temple",
	"HauntedWoods": "Garden of Terror",
	"IndustrialDistrict": "Industrial District",
	"LostCavern": "Lost Cavern",
	"Shrines": "Infernal Shrines",
	"SilverCity": "Silver City",
	"TowersOfDoom": "Towers of Doom",
	"Volskaya": "Volskaya Foundry",
	"Warhead Junction": "Warhead Junction",
}

# Hero display name -> gameplay role (final HotS classifications)
HERO_ROLES: dict[str, str] = {
	"Abathur": "Support",
	"Alarak": "Melee Assassin",
	"Alexstrasza": "Healer",
	"Ana": "Healer",
	"Anduin": "Healer",
	"Anub'arak": "Tank",
	"Artanis": "Bruiser",
	"Arthas": "Tank",
	"Auriel": "Healer",
	"Azmodan": "Ranged Assassin",
	"Blaze": "Tank",
	"Brightwing": "Healer",
	"Cassia": "Ranged Assassin",
	"Chen": "Bruiser",
	"Cho": "Tank",
	"Chromie": "Ranged Assassin",
	"D.Va": "Tank",
	"Deathwing": "Bruiser",
	"Deckard": "Healer",
	"Dehaka": "Bruiser",
	"Diablo": "Tank",
	"E.T.C.": "Tank",
	"Falstad": "Ranged Assassin",
	"Fenix": "Ranged Assassin",
	"Gall": "Ranged Assassin",
	"Garrosh": "Tank",
	"Gazlowe": "Bruiser",
	"Genji": "Ranged Assassin",
	"Greymane": "Ranged Assassin",
	"Gul'dan": "Ranged Assassin",
	"Hanzo": "Ranged Assassin",
	"Hogger": "Bruiser",
	"Illidan": "Melee Assassin",
	"Imperius": "Bruiser",
	"Jaina": "Ranged Assassin",
	"Johanna": "Tank",
	"Junkrat": "Ranged Assassin",
	"Kael'thas": "Ranged Assassin",
	"Kel'Thuzad": "Ranged Assassin",
	"Kerrigan": "Melee Assassin",
	"Kharazim": "Healer",
	"Leoric": "Bruiser",
	"Li Li": "Healer",
	"Li-Ming": "Ranged Assassin",
	"Lt. Morales": "Healer",
	"Lunara": "Ranged Assassin",
	"Lúcio": "Healer",
	"Maiev": "Melee Assassin",
	"Mal'Ganis": "Tank",
	"Malfurion": "Healer",
	"Malthael": "Bruiser",
	"Medivh": "Support",
	"Mei": "Tank",
	"Mephisto": "Ranged Assassin",
	"Muradin": "Tank",
	"Murky": "Melee Assassin",
	"Nazeebo": "Ranged Assassin",
	"Nova": "Ranged Assassin",
	"Orphea": "Ranged Assassin",
	"Probius": "Ranged Assassin",
	"Qhira": "Melee Assassin",
	"Ragnaros": "Bruiser",
	"Raynor": "Ranged Assassin",
	"Rehgar": "Healer",
	"Rexxar": "Bruiser",
	"Samuro": "Melee Assassin",
	"Sgt. Hammer": "Ranged Assassin",
	"Sonya": "Bruiser",
	"Stitches": "Tank",
	"Stukov": "Healer",
	"Sylvanas": "Ranged Assassin",
	"Tassadar": "Ranged Assassin",
	"The Butcher": "Melee Assassin",
	"The Lost Vikings": "Support",
	"Thrall": "Bruiser",
	"Tracer": "Ranged Assassin",
	"Tychus": "Ranged Assassin",
	"Tyrael": "Tank",
	"Tyrande": "Healer",
	"Uther": "Healer",
	"Valeera": "Melee Assassin",
	"Valla": "Ranged Assassin",
	"Varian": "Bruiser",
	"Whitemane": "Healer",
	"Xul": "Bruiser",
	"Yrel": "Bruiser",
	"Zagara": "Ranged Assassin",
	"Zarya": "Support",
	"Zeratul": "Melee Assassin",
	"Zul'jin": "Ranged Assassin",
}

# ARAM-exclusive map internal IDs (for mode detection without localized names)
ARAM_MAP_IDS = frozenset({"LostCavern", "IndustrialDistrict", "SilverCity", "BraxisOutpost"})

# ARAM-exclusive map English display names (derived from IDs above)
ARAM_MAP_NAMES = frozenset(MAP_NAMES[mid] for mid in ARAM_MAP_IDS if mid in MAP_NAMES)
